server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nareshmiriyala/config-repo
          search-paths: licensingservice
          username: ncmiriyala@gmail.com
          password: naresh277644
encrypt:
  key-store:
    location: server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
